### PR TITLE
Feature/azure sso

### PR DESCRIPTION
**Pull request by parhammmm**
in order to get things to work you will need to point your local dev ip address/host (e.g. localhost or 127.0.0.1) to `gcat` in your host files

### CODE REVIEW

**Comment by RomeshA** [comment]
Oh also this PR should be changed to merge into `develop` rather than `framework-db-test`

**Comment by parhammmm** [comment]
@RomeshA regarding your questions:

1. Those tables are part of the library I'm using for the OAuth2 flow. They have their own uses depending on the OAuth2 implementation. It's better to leave them in as they have little overhead but taking their definitions out will probably cause a few reference errors.

2. Ok I'll have a look at it, but let's not wait it before we merge, that can be a separate PR. But read answer to 3 first :)

3. That issue is taken care of by social auth see here: https://github.com/python-social-auth/social-core/blob/master/social_core/pipeline/user.py#L9 but if we want to store the email as username it's only a configuration see here: https://github.com/python-social-auth/social-core/blob/master/social_core/pipeline/user.py#L15

4. I think that's just Microsoft remembering your login details, I'll look into it but I think that's the intended behaviour

**Comment by RomeshA** [comment]
@parhammmm That all sounds good. So if we just set `USERNAME_IS_FULL_EMAIL` then that would solve (2) and (3) at the same time? Shall we do that?

**Comment by parhammmm** [comment]
@RomeshA sure thing, I'll push a commit for it now

**Pull request merged**
